# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ar_mock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('method', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_mock.Server'),
        ),
        migrations.AddField(
            model_name='queryparam',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_mock.Resource'),
        ),
        migrations.AddField(
            model_name='pathparam',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_mock.Resource'),
        ),
    ]
