# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ar_mock', '0003_remove_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='protocol',
            field=models.CharField(default='https', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pathparam',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathParams', to='ar_mock.Resource'),
        ),
        migrations.AlterField(
            model_name='queryparam',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryParams', to='ar_mock.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ar_mock.Server'),
        ),
    ]
